### ISSUE TITLE
api info

### ISSUE THREAD

**Issue by santalucial** [kakaroto/fvtt-module-api#2]
Where do i find a list of apis? i can't seem to get it anywhere

**Comment by kakaroto** [comment]
Since this isn't the actual JS API, there is no documentation for it. The API it lets you access is the raw websocket API. The best way to get it is to look at the foundry.js code wherever the `game.socket` is used. Also, you can look at the network tab in the dev tools and see the messages going back and forth in the websocket queue.
If you can't do that or figure it out, then this is probably not meant for you to use, because it's quite a low level tool to be used carefully with good knowledge of how the internal server API works.
I hope that helps.

**Comment by santalucial** [comment]
Very helpful, thank you
