### ISSUE TITLE
Still working in 9.X?

### ISSUE THREAD

**Issue by begna112** [kakaroto/fvtt-module-api#5]
I see this module hasn't been updated in a while and the manifest only specifies up to 0.8.99. Is it still working for 0.9.X?

The foundry packages page only says up to 0.7. I don't know who maintains that page. https://foundryvtt.com/packages/api

**Comment by kakaroto** [comment]
As far as I know it doesn't need an update, as it's pretty simple in how it works and should still work.
I don't use it, I just created it because I thought it would be an interesting exercise after some people showed an interest in the feature. Best way to know is to test it. Install it and go to `https://example.com/modules/api/api.html?name=world` as explained in the README to see if it works.
(And it looks like it does indeed still work)
![image](https://user-images.githubusercontent.com/27990/165431024-302c8ae2-7147-44ca-b5ad-c6c6b4aa8e85.png)

**Comment by kakaroto** [comment]
I just pushed an update to it which sets the compatibility to v9
